### ISSUE TITLE
stylelintでno-descending-specificityのルールを有効化する

### ISSUE THREAD

**Issue by munierujp** [tokyo-metropolitan-gov/covid19#1937]
## 改善詳細 / Details of Improvement
- `stylelint.config.js`でstylelintの[no-descending-specificity](https://stylelint.io/user-guide/rules/no-descending-specificity)のルールが無効化されているが、バグを避けるためにも本来有効であるのが望ましいので有効化する

## 期待する見せ方・挙動 / Expected behavior
- stylelintでno-descending-specificityのルールが有効になっている

## 📝 関連する プルリクエスト / Related Pull requests
- #1700

**Comment by munierujp** [comment]
こちら #1700 の作業を行う際に影響範囲が大きいため一時的に無効にしたのですが、バグを避けるためにも本来有効であるのが望ましいので、どなたか作業していただけるとありがたいです。
ファイル数が結構多いので、一気にやらずにあらかじめ各ファイルでno-descending-specificityのルールに違反しないように修正してから`stylelint.config.js`を変更したほうがいいかもしれません。

**Comment by macropygia** [comment]
> 修正してからstylelint.config.jsを変更

ひとまず `warning` にしておくとか。

> どなたか作業していただけるとありがたいです

`StaticCard` と `*CasesTable` は担当します。PRはこのissue向けでよろしいでしょうか。

なお、このルールには[公式ドキュメントの「DOM Limitations」の項](https://stylelint.io/user-guide/rules/no-descending-specificity#dom-limitations)に書かれている仕様上の限界があるため、必要に応じて `/* stylelint-disable no-descending-specificity */` で無効化しますが、問題ないでしょうか。

**Comment by munierujp** [comment]
@macropygia 
>ひとまず warning にしておくとか。

その手がありましたね！（最初からそうしておけばよかった……
それを踏まえて、Issueは以下のように分けるのがいいかと思います。

- no-descending-specificityのルールをwarning扱いに変更する
- <component-name>.vueのno-descending-specificityのwarningを解消する（warningが出ているコンポーネント分Issueを作成）

> なお、このルールには公式ドキュメントの「DOM Limitations」の項に書かれている仕様上の限界があるため、必要に応じて無効化しますが問題ないでしょうか。（個人的には割と高頻度で発生する印象です）

コンポーネントによってはその対応でいいかと思います（正直CSSのそのあたりの仕様に疎いので、自分でやらずにIssueだけ立てているという事情もあります）

**Comment by munierujp** [comment]
stylelintでwarningがあると、GitHub Actions上で動いている https://github.com/reviewdog/action-stylelint でエラー扱いになってしまうようです。

**Comment by macropygia** [comment]
うーん、思いつくのはreviewdogのstylelintの設定に `level: warning` を入れるとどうなるか、くらいですかね。

```yaml
  stylelint:
    name: check_stylelint_error
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: stylelint review
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          stylelint_input: '**/*.{css,scss,vue}'
          level: warning
```
