### ISSUE TITLE
ja.json 以外の /assets/locales/{lang}.json を commit 不可にする

### ISSUE THREAD

**Issue by halsk** [tokyo-metropolitan-gov/covid19#2016]
## 改善詳細 / Details of Improvement
- #1985 で書かれている通り、ja.json のみは GitHub で登録し、その他のファイルは Transifex 経由でないと登録できない、という運用が混乱を招いている
- 周知は必要だが、「ドキュメントをよく読め」という運用自体を改めたい
- この際、ja.json 以外の {lang}.json はコミットできなくしてしまえば良いのではないか

## 期待する見せ方・挙動 / Expected behavior
- pre-commit hook を使えばなんとかなる？(参考: [gitで特定のファイルの更新を禁止する | Qiita](https://qiita.com/ryounagaoka/items/3e7a1b44d43ad0547d4f))
- ただし、Transifex からの pull request は受けられるようにする必要があるので注意 （例：#2008 ）

**Comment by macropygia** [comment]
hooksが辛そうならactionで警告とか？
hotfixでは直接編集も致し方なしとのことなので、制限はdevブランチだけですよね。

```yaml
name: lang files

on:
  pull_request:
    branches:
      - development
    paths:
      - 'assets/locales/*.json'
      - '!assets/locales/ja.json'

jobs:
  transifex:
    name: only Transifex can edit
    runs-on: ubuntu-18.04
    steps:
      - name: are you Transifex?
        if: github.actor != 'transifex-integration'
        run: exit 1
```

※自信なし
