### ISSUE TITLE
Release 自動作成のエラー改善

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#2115]
## 改善詳細 / Details of Improvement
- GitHub Actions でリリースを作成する際にエラーが発生することがある
- 同名のリリースがすでに存在しているのが原因だと思われます https://github.com/actions/create-release/issues/41#issuecomment-585900886
- 作成済みのリリースの名称を手動で変えてもいいですが、リリース担当者の作業が増えるので自動化したほうが良さそう

## スクリーンショット / Screenshot
3月22日のリリースログ
ref: https://github.com/tokyo-metropolitan-gov/covid19/runs/526124591?check_suite_focus=true

![スクリーンショット 2020-03-23 20 52 58](https://user-images.githubusercontent.com/5207601/77314101-5fc46200-6d48-11ea-84de-f41e8b2fab6f.png)

3月21日にすでに同名のリリースが作られていました。
ref: https://github.com/tokyo-metropolitan-gov/covid19/releases

![スクリーンショット 2020-03-23 20 51 52](https://user-images.githubusercontent.com/5207601/77314118-63f07f80-6d48-11ea-99b5-91265aa2fcbf.png)

## 期待する見せ方・挙動 / Expected behavior
- リリースが自動で作成されること

## 動作環境・ブラウザ / Environment
- GitHub Actions

**Comment by shgtkshruch** [comment]
`relsase_name` が Release ごとにユニークになれば良さそう。

https://github.com/tokyo-metropolitan-gov/covid19/blob/15465812497027ae94c05f9581079e4e7f227cc9/.github/workflows/deploy.yml#L45

`github.ref` はワークフローを起動したイベントを元に、ブランチやタグを引いてくる。
https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

Release 作成に利用している [actions/create-release](https://github.com/actions/create-release) の README を見ると tag を push した際に `github.ref` を参照している。

```yml
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
```
この場合はタグの名前がユニーク性を担保するのでエラーにならなそう。
（今は `on: push: branches: master`）

改善案
1. リリース作成をキックするワークフローを tag ベースで起動する（`on: push: tags`）
1. `release_name` を指定するコードで、commit 時刻などから`Release YYYY/DD/MM` 形式の文字列を生成する
