### ISSUE TITLE
 `yarn dev` 時に `::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.` が出力される

### ISSUE THREAD

**Issue by Murayu0225** [tokyo-metropolitan-gov/covid19#7478]
## 起こっている問題 / The Problem

- `yarn dev` 時に `::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.` が出力される．
- エラーではないのでタイトルと内容を修正しました．

## スクリーンショット / Screenshot

<img width="822" alt="スクリーンショット 2022-09-10 17 01 38" src="https://user-images.githubusercontent.com/37988559/189474786-c2bcaa10-d2ec-4162-acee-4b5c399a3369.png">

## 期待する見せ方・挙動 / Expected Behavior

- 調べたところ

```scss
  ::v-deep .v-icon {
    color: $green-1;
  }
```

```scss
  ::v-deep(.v-icon) {
    color: $green-1;
  }
```

とすることにより解決することができる．

## 起こっている問題の再現手段 / Steps to Reproduce

1. `yarn install`
2. `yarn dev`

## 動作環境・ブラウザ / Environment

- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer
